# Generated by Django 5.2.4 on 2025-07-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_nutrition_carbs_nutrition_fat_nutrition_fiber_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calorie_goal", models.PositiveIntegerField(default=2000)),
                ("protein_goal", models.PositiveIntegerField(default=50)),
                ("carb_goal", models.PositiveIntegerField(default=250)),
                ("fat_goal", models.PositiveIntegerField(default=70)),
                ("fiber_goal", models.PositiveIntegerField(default=30)),
                ("water_goal", models.PositiveIntegerField(default=2000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
