# Generated by Django 5.2.4 on 2025-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_waterlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="cheat_day",
            field=models.PositiveSmallIntegerField(
                default=4, help_text="0=Monday, 6=Sunday"
            ),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="cheat_day_last_changed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
